In [1]:
print("We are learning Numpy")   ## shift + enter to run

We are learning Numpy


In [2]:
import numpy as np

In [3]:
### Create an Array (2D Array)

In [ ]:
a1 = np.array([[4,8,9],[8,9,6],[2,3,6],[7,6,5],[1,3,5]])
a1

In [ ]:
a1.shape

In [ ]:
a1.ndim

In [ ]:
a1.dtype

In [ ]:
a1.max()

In [ ]:
a1.min()

In [ ]:
a1

In [ ]:
a1.argmax()

In [ ]:
a1.argmin()

In [20]:
a1.sum()

82

In [ ]:
a1.sum(axis=0)  ## column wise addition

In [ ]:
a1.sum(axis=1)  ## row wise addition

In [24]:
### Picking any element from array (slicing of array)

In [ ]:
a1

In [ ]:
a1[3]

In [ ]:
a1[:]

In [ ]:
a1[2:5]   ## index 2 to index 4

In [ ]:
a1[:4]    ## index 0 to index 3

In [ ]:
a1[3:]   ## index 3 to last 

In [ ]:
a1

In [ ]:
a1[1]

In [ ]:
a1[1][1]

In [ ]:
a1[1,1]

In [ ]:
a1[1:4,1:3]

In [40]:
### Linspace Function - Generate equidistant number

In [ ]:
a2 = np.linspace(1,100,30)   ## (start,stop,no.of samples)
#a2 = a2.astype('int')
a2

In [ ]:
a2 = np.linspace(1,100,10)
a2

In [ ]:
a2=np.linspace(1,10,3)
a2

In [ ]:
### Arange Function
a3 = np.arange(1,102,5)   #(start,stop,difference)
a3

In [ ]:
len(a3)

In [63]:
a4=np.arange(1,100,5)
a4

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [55]:
### Random Numbers

In [ ]:
np.random.randint(100)   ## any random number b/w 0-99

In [82]:
np.random.seed(2)
np.random.randint(100) 

40

In [84]:
np.random.randint(10000,200000)   ## any random number b/w 10000-199999

105816

In [86]:
np.random.randint(10,1000,10)

array([309, 476,  85, 370, 273, 684, 443, 617, 597, 735])

In [88]:
np.random.seed(2)
np.random.randint(10,1000,(4,5))   ## random array (4x5)

array([[178, 537, 503, 594, 544],
       [309, 476,  85, 370, 273],
       [684, 443, 617, 597, 735],
       [ 57, 841, 297, 740, 414]])