In [30]:
import numpy as np

In [31]:
inputs = np.array([[0,0,1],[1,0,1],[1,1,0],[0,1,0]])
inputs

array([[0, 0, 1],
       [1, 0, 1],
       [1, 1, 0],
       [0, 1, 0]])

In [32]:
outputs = np.array([[0],[1],[1],[0]])
outputs

array([[0],
       [1],
       [1],
       [0]])

In [33]:
np.random.seed(10)
weights = np.random.random((3,1))  ## random number b/w 0-1
weights

array([[0.77132064],
       [0.02075195],
       [0.63364823]])

In [34]:
sum = np.dot(inputs,weights) + 0.02  ### 0.02-bias
sum

array([[0.65364823],
       [1.42496888],
       [0.81207259],
       [0.04075195]])

In [35]:
## Activation Function
def activation(x):
  return 1/(1+np.exp(-x))

In [36]:
pred_op = activation(sum)
pred_op

array([[0.65783211],
       [0.8061162 ],
       [0.69255099],
       [0.51018658]])

In [37]:
pred_op.round()

array([[1.],
       [1.],
       [1.],
       [1.]])

In [38]:
### Calculate Error
sum = np.dot(inputs,weights) + 0.02
pred_op = activation(sum)
error = outputs - pred_op
error

array([[-0.65783211],
       [ 0.1938838 ],
       [ 0.30744901],
       [-0.51018658]])

In [39]:
def gradient(x,a):
  return a * x*(1-x)

In [44]:
sum = np.dot(inputs,weights) + 0.02
pred_op = activation(sum)
error = outputs - pred_op
cng_in_wt = gradient(pred_op,error)  ## gradient descent
weights = weights + np.dot(inputs.T,cng_in_wt)  ## back propogation
error

array([[-0.60353787],
       [ 0.20073967],
       [ 0.2932569 ],
       [-0.47955358]])

In [ ]:
inputs.T.shape

In [ ]:
cng_in_wt.shape

In [45]:
### Training of network
for i in range(500):
  sum = np.dot(inputs,weights) + 0.02
  pred_op = activation(sum)
  error = outputs - pred_op
  cng_in_wt = gradient(pred_op,error)  ## gradient descent
  weights = weights + np.dot(inputs.T,cng_in_wt)  ## back propogation

In [ ]:
error

In [ ]:
pred_op

In [50]:
pred_op.round()

array([[0.],
       [1.],
       [1.],
       [0.]])

In [51]:
weights

array([[ 6.31598997],
       [-2.99154618],
       [-2.99154409]])

In [52]:
cng_in_wt

array([[-0.0022635 ],
       [ 0.00112407],
       [ 0.00112407],
       [-0.00226349]])